### ISSUE TITLE
Add a slider component

### ISSUE THREAD

**Issue by meatballs** [anvilistas/anvil-extras#26]
Something similar to
https://anvil.works/library/slider
https://anvil.works/forum/t/slider-with-dynamic-ticks-and-labels/5761

**Comment by hugetim** [comment]
Can I submit Allan's ([slightly modified](https://anvil.works/forum/t/slider-with-dynamic-ticks-and-labels/5761/4?u=hugetim)) component as a pull request? (The thing I'm not sure about is whether I would need to add the Apache 2.0 license, or how I would do that?)

**Comment by meatballs** [comment]
I haven't looked in detail, so I don't know what licence that app is under nor whether it fits with our guidelines.

**Comment by meatballs** [comment]
I've had a quick look and I think there are two problems:

1. The licence is different to the one we use in this library and I don't have sufficient expertise to understand the implications of that.
2. I don't see anything that implements a unique id which is necessary for more than one copy of the component to be used in a form

I suspect both those things could be resolved but, at the moment, I don't think we could merge that code into here.

**Comment by s-cork** [comment]
https://refreshless.com/nouislider/

**Comment by s-cork** [comment]
Here's a rough version of a slider:
https://MMWRBSX27QJCPCG3.anvil.app/CSSCSXUBGQ7I4FGE2FW6T2I3

It might be a bit much.

I wasn't sure what to call the value/values property. Which would differ if you had multiple slider handlers!
In the end i went with `data` but I wasn't convinced on this name...

**Comment by meatballs** [comment]
I just get an app error when I try to have a look at that

**Comment by meatballs** [comment]
aha! Now I don't!

**Comment by meatballs** [comment]
> I wasn't sure what to call the value/values property. Which would differ if you had multiple slider handlers!
> In the end i went with data but I wasn't convinced on this name...

handle_values ?

**Comment by s-cork** [comment]
sorry yeah - i'm still working on it at the same time - so I probably wrote in a bug!

how about this:
```text
handle_values: a list of numbers
formatted_values: a list of strings - formatted based on the formatter

value: the value of the first handle
formatted_value: the formatted version of the handle based on the formatter
```
I can't decide what I like.
The use case is probably going to be just for a single handle most of the time.

Also...
Is the formatting too much?
I based in on the javascript component which uses a dictionary to define the formats

**Comment by meatballs** [comment]
This looks good:
```
handle_values: a list of numbers
formatted_values: a list of strings - formatted based on the formatter

value: the value of the first handle
formatted_value: the formatted version of the handle based on the formatter
```

I agree that the vast majority of use will be with one slider and this makes that nice and simple.

**Comment by meatballs** [comment]
I can't see what you've done with the formatting. I can only see the end result.

**Comment by s-cork** [comment]
I've just changed the formatting actually. Before I was using the suggested JavaScript library from the author. But it was a json mess. 

I've adjusted it so that the property `format` can be either a format spec or a str that gets called with `.format()`

Valid values would be `.2f` or `£{:.2f}`. This makes it mor pythonic I think.

`tooltips` is now a Boolean and just uses the same formatting. 
`pips_format` was removed and also uses the same formatting.

If your looking at the latest version. The random property names is me playing with the api. 

The thing I think is most confusing at the moment is the start value. Which basically determines the number of handles and their initial positions. It's a required field otherwise it blows up. I'm thinking maybe `initial_values` might be a better name. 

I also want to add a feature so that when the initialisation blows up the error message is displayed in place of the component. At the moment it just goes blank.

**Comment by meatballs** [comment]
sorry if I'm being a bit thick, but where do I see the code? I can't see a branch on here, so I've just been following your link to the demo of it so far.

**Comment by s-cork** [comment]
ah yes - sorry you'd have to reclone the clone link above. I can move it to a pr branch as a draft, now that I'm a bit further along.

**Comment by meatballs** [comment]
it's not a clone link, it just fires up the app

**Comment by s-cork** [comment]
🤦 
https://anvil.works/build#clone:MMWRBSX27QJCPCG3=BLZXW2JFE65SH5UPCN5JJDHM
