### ISSUE TITLE
Multiselect does not refresh data bindings on change

### ISSUE THREAD

**Issue by erikcw** [anvilistas/anvil-extras#307]
**Describe the bug**
When a Multiselect has `selected` bound to a value in `self.item['...']`, it doesn't run `self.refresh_data_bindings()` on change.  Doing so in a change event leads to some sort of infinite loop and crashes the app/browser.

**To Reproduce**
Steps to reproduce the behavior (including a clone link when applicable):

Here is an example to clone: https://anvil.works/build#clone:V7LJDPUIVR4GLXCS=X37GLK3PCQX35FC22C7XWP6Z

**Expected behavior**
Like other Anvil form elements, changes should refresh data bindings.

**I am considering making a PR for this issue**
No

**Comment by erikcw** [comment]
@s-cork This PR is a significant improvement.  However, 2 issues still seem to remain.

1)  It looks like `self.refresh_data_bindings()` still isn't being run `onChange` or `onClose` by default like other anvil components that are using data bindings typically do.  Adding it in a change method works, but is a deviation from Anvil norms.
2)  More importantly, if `selected` is bound to `self.item[...]` in the IDE, and the item has a value on init (`self.item['selected'] = ['a']` ), the state of the multiselect remains empty/null.  I've updated my example above to reflect this.

**Comment by s-cork** [comment]
Do you have an example of a component where you don't need to call `refresh_data_bindings()`?

I think that might be a mistaken expectation. Try the same thing with a TextBox and a Label and you'll still need to call `refresh_data_bindings()` in the TextBox change event. 

That's what `anvil_extras.utils` auto_refreshing is designed to solve. 

Thanks for the update clone. I'll take a look and the second point.

**Comment by erikcw** [comment]
Actually, I think you are right about my mistaken expectation.  I just added the Native Anvil DropDown, and it doesn't `refresh_data_bindings()` automatically.

Let me know your thoughts on the 2nd point.

**Comment by rhurlbatt** [comment]
I suspect there is an edge case issue here with this code in the Dev Branch. Previous code that was working now is not. It seems that the MultiSelect is no longer firing its change event when that event was set in code. I had this to set the change event in the form show which worked before the weekend.

`self.supplier_msdd.set_event_handler('change', self.supplier_msdd_change)`

Now the change event no longer fires. I have rolled back my version to v2.01 and all seems to be working again.

I am not meant to be in the office today so won't get to have a look at this until tomorrow. If needed I can try build a minimal example then.

**Comment by s-cork** [comment]
@rhurlbatt - This is an intentional change rather than a regression.

It causes infinite loops if you:
- call `refresh_data_bindings()`
- inside the change handler 
- when there is writeback on the `selected` property
- (the change event will keep firing)

The behaviour on the dev branch now matches other anvil components.
e.g. if you set the `selected_value` property on an Anvil dropdown in code the change event doesn't fire.

I can update the change log to make this clear.

I'm happy to consider two options:
- stick with the dev branch
  - it's correct when compared with all other anvil components
- add an event arg that signals whether the event was from code or user
  - this can largely be ignored by most users
  - calling `refresh_data_bindings()` would only work when the event type was from the user

@erikcw - if we went with the second options your code would look something like:

```python
def mulit_select_dd_change(self, **event_args):
    if event_args["event_type"] == "user":
        self.refresh_data_bindings()
```


it's certainly not as intuitive when compared with other anvil components so i'm not sold on it, but it might be a reasonable compromise.

Also tagging @meatballs

**Comment by erikcw** [comment]
Ideally we would maintain parity of experience with the other Anvil components as much as possible.  

Assuming I'm understanding @meatballs problem correctly -- I tried setting the `selected_value` of a native Anvil DropDown programmatically (`self.drop_down.selected_value = 'foo'`) and it didn't trigger the attached change event.

**Comment by erikcw** [comment]
I also just tested the "Select All" feature, which didn't write it's updates back to the `self.item`, but individually clicking each item did.

**Comment by rhurlbatt** [comment]
Thanks @s-cork. I am very much in favour of making things as closely aligned to Anvil components as possible so I like the idea of keeping the dev branch. This does feel like a breaking change though so I feel this needs to be highlighted in the release notes.

**Comment by meatballs** [comment]
I think we should stick with the dev branch and match the standard behaviour. I don't agree this is a breaking change (which would require a v3 release). It's a bugfix to prevent inifinite loops.

The fact that there is code out there which makes use of an unintended bug doesn't make this a breaking change. It just means we need to be clear in the changelog.

**Comment by s-cork** [comment]
updated change log on #313

**Comment by rhurlbatt** [comment]
Understood and thanks for addressing it.
