### ISSUE TITLE
MultiSelectDropDown drops an error message when starting app.

### ISSUE THREAD

**Issue by Csirobi** [anvilistas/anvil-extras#415]
**Describe the bug**
The MultiSelectDropDown component can not run, because drops an error message.

**Version**
Published

**To Reproduce**
1. Login to your account and create a new & empty app.
2. In the Design tab, drag&drop a MultiSelectDropDown component to the Form in the app.
3. In the Code tab, initialize the items of this component.
4. Try to run the app.
5. See the error:
--
ExternalError: [object Event]

    at app/anvil_extras/utils/_component_helpers.py:72
    called from app/anvil_extras/utils/_component_helpers.py:43
    called from app/anvil_extras/MultiSelectDropDown/__init__.py:40

**Expected behavior**
The app is running..

**Additional context**
Browser: Firefox v112.2

**Comment by s-cork** [comment]
Is this consistent? or a one off?

it might be that the cdn failed to load.
I can't reproduce this locally
Does it happen in other browsers?
Could you see if you can find the error in the dev tools console so that we can look at what the actual error message is

You might want to add some logging statements so you can isolate the error
If importing the module is enough to trigger this than try doing

```python
print("BEFORE IMPORT")
from anvil_extras.MultiSelectDropDown import MultiSelectDropDown
print("AFTER IMPORT")
```

The print statements should appear in the browser console which will help to isolate the error in the console

**Comment by Csirobi** [comment]
Hi,

I have started to debug it based on your comment, and I may have found the core of it:
the jsdelivr.net domain has not been allowed to our network..
After modification of the firewall rule, this multiselect component is able to show in the browser..

Thx
