### ISSUE TITLE
Add upgrade instructions to Installation docs

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-extras#42]
It may be pretty simple, but it wasn't obvious to me beforehand that this would work without a hitch (as long as the component names and API for the features you're using are stable between versions):

1. Clone the new version of Anvil Extras.
2. Remove the dependency on the old version from your app.
3. Add a dependency to the new version.

**Comment by s-cork** [comment]
That's not the way I'd recommend updating.
It's a massive pain to update a dependency this way if you're using the components in the designer
since you end up having to remove those components and then re add them.

I'd recommend updating through git. 

This is the way i've suggested doing updates on other dependencies before
the first time you update
clone your version of the dependency locally
```bash
git remote add upstream git@github.com:anvilistas/anvil-extras.git
git fetch upstream
git reset --hard upstream/master
git push origin master -f
```
subsequent times:

```bash
git pull upstream
git push -f origin master
```

Though @meatballs  those instructions would need a slight tweak given the different branch names between an anvil app and this repo (main vs master)

(It might be worth having a master branch on this repo while anvil doesn't support a main branch)

**Comment by meatballs** [comment]
I'll write up the git process, including how to push one branch to another with a different name.
