### ISSUE TITLE
Popover Not Working on Disabled TextBox Components

### ISSUE THREAD

**Issue by josephreber** [anvilistas/anvil-extras#427]
**Describe the bug**
Popovers fail to appear when applied to TextBox components that are disabled (ex: `textBox.enabled = False`). The popovers appear correctly on the same component when enabled = True and popovers appear correctly on disabled DropDown components. 

**Version**
v2.2.0

**To Reproduce**
1. Add a TextBox component to a form. In this example, I'll name the TextBox component self.textBox.
2. In the form's __init__ function add the following two lines of code:
  `self.textBox.enabled = False`
  `self.textBox.popover(content='Popover text here', trigger='hover')`
4. Run the application and hover over the TextBox. No popover appears.

**Expected behavior**
On hover (or any other defined trigger) the TextBox component should show a popover.

**Comment by s-cork** [comment]
This won't work because there are no pointer events on the disabled text box and so the hover event doesn't fire.

You'll need to wrap the textbox in a container like a `FlowPanel` or a `LinearPanel` and add the popover to the container instead.

I'll leave this open until we document this behaviour.
