### ISSUE TITLE
Auto-refresher removes reference relationship

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-extras#89]
In the auto_refreshing Demo code, self.item is initialized like this:
```python
self.item = self.default_item = dict(tally=100, counter=0,)
```
There are buttons to change item["tally"] and item["counter"], and the label components displaying these values are auto-refreshed. Then there is another button that resets the tally and counter to the default values via this line:
```python
self.item = self.default_item
```
This works as intended, but the trouble is that this actually shouldn't work--and it indeed doesn't work without the auto-refreshing enabled. The reason is that self.item was initialized to be equal to self.default_item by *reference*, so any changes to self.item should also change self.default_item. The fact that it doesn't when auto-refreshing is triggered by changes to self.item seems to be a subtle bug (or undocumented side effect) in the auto-refreshing functionality.

**Comment by meatballs** [comment]
[L42, _auto_refreshing.py](https://github.com/anvilistas/anvil-extras/blob/a707510f76d9cdc305965d1c9bdff7c203026c3a/client_code/utils/_auto_refreshing.py#L42) passes the incoming `item` to the `__init__` of `BindingRefreshDict`

Since `BindingRefreshDict` is a subclass of `dict`, this is equivalent to passing it to the `dict` function. The effect is the same as:

```
test = {"a": 1, "b": 2}
test2 = dict(test)

test2["c"] = 3

test2
{"a": 1, "b": 2, "c": 3}

test
{"a": 1, "b": 2}
```

Perhaps we just need to explain this in the docs?

**Comment by s-cork** [comment]
An alternative approach might be to proxy the original object?
That would mean the example would have to do this instead

```python
item = {"a": 1, "b": 2}
self.default_item = item.copy()
self.item = item
```

It has the benefit that self.item can be a table row and so setting a value would update the original object and the form
```
>>> item = {"a": 1, "b": 2}
>>> self.item = item
>>> self.item['a'] = 3
>>> item
{"a": 3, "b": 2}
```

It might be slightly confusing if you had two references to item
```
>>> self._item = item
>>> self.item = item
>>> self.item is self._item
False
```

What do you think @meatballs?

It would probably also mean we wouldn't have to include the code that wories about sub forms using the same item since we would essentially be proxying the original item.

**Comment by meatballs** [comment]
To be clear - are you suggesting that we leave the code itself unchanged but simply change the demo? (I am wondering why on earth I didn't use a copy in the first place when I did that demo. Laziness, I suspect).

**Comment by s-cork** [comment]
i was actually suggesting we could change the internal code so that, instead of subclassing from dict, we should proxy the original item we are given.

e.g.
```python
class RefreshProxyItem:
    def __init__(self, item):
        self._item = item
    def __getitem__(self, key):
        return self._item[key]
    def __setitem__(self, key, val):
        self._item[key] = val
        self._refresh_data_bindings()
    def __iter__(self):
        return self._item.__iter__()
    def __getattr__(self, attr):
        return getattr(self._item, attr)
````

The problem with this approach would be all the magic methods we'd need to create.
I guess we could create the ProxyClass on the fly based on the item itself.

**Comment by meatballs** [comment]
Right. Gotcha!

That feels a little OTT to me. I don't think there's anything inherently wrong with what we have now. If we change the demo code to use `copy` and add some explanation to the docs, I reckon that's ok. You?

**Comment by s-cork** [comment]
yeah - agree.
